# Generated by Django 3.1 on 2020-09-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='angry',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='happy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='sad',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='surprised',
            field=models.FloatField(default=0.0),
        ),
    ]
