# Generated by Django 3.1 on 2020-09-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200901_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='seomyeon',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=50)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('search_word', models.CharField(max_length=50, null=True)),
                ('hashtags', models.CharField(max_length=400, null=True)),
                ('menu', models.CharField(max_length=4000, null=True)),
                ('like', models.FloatField()),
                ('happy', models.FloatField()),
                ('sad', models.FloatField()),
                ('angry', models.FloatField()),
                ('surprised', models.FloatField()),
                ('count', models.IntegerField()),
                ('WEIGHTED_VOTE', models.FloatField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='정보없음', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='angry',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='happy',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='sad',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='surprised',
            field=models.FloatField(),
        ),
    ]
