# Generated by Django 3.1 on 2020-09-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200902_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seomyeon',
            old_name='hashtags',
            new_name='가게해시태그',
        ),
        migrations.RenameField(
            model_name='seomyeon',
            old_name='search_word',
            new_name='검색어',
        ),
        migrations.RenameField(
            model_name='seomyeon',
            old_name='menu',
            new_name='메뉴',
        ),
        migrations.RenameField(
            model_name='seomyeon',
            old_name='name',
            new_name='이름',
        ),
        migrations.RenameField(
            model_name='seomyeon',
            old_name='category',
            new_name='카테고리',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='category',
            new_name='user_category',
        ),
        migrations.RemoveField(
            model_name='seomyeon',
            name='count',
        ),
        migrations.RemoveField(
            model_name='seomyeon',
            name='like',
        ),
        migrations.RemoveField(
            model_name='seomyeon',
            name='x',
        ),
        migrations.RemoveField(
            model_name='seomyeon',
            name='y',
        ),
        migrations.AddField(
            model_name='seomyeon',
            name='sentiment',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='seomyeon',
            name='게시글수',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seomyeon',
            name='경도',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='seomyeon',
            name='위도',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='seomyeon',
            name='좋아요',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='pw',
            field=models.CharField(default='123123', max_length=20),
        ),
        migrations.AlterField(
            model_name='seomyeon',
            name='WEIGHTED_VOTE',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='seomyeon',
            name='angry',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='seomyeon',
            name='happy',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='seomyeon',
            name='sad',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='seomyeon',
            name='surprised',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='angry',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='happy',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='sad',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='surprised',
            field=models.FloatField(max_length=10),
        ),
    ]
