# Generated by Django 3.1 on 2020-09-02 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200902_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seomyeon',
            old_name='카테고리',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='seomyeon',
            old_name='게시글수',
            new_name='count',
        ),
        migrations.RenameField(
            model_name='seomyeon',
            old_name='가게해시태그',
            new_name='hashtags',
        ),
        migrations.RenameField(
            model_name='seomyeon',
            old_name='좋아요',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='seomyeon',
            old_name='메뉴',
            new_name='menu',
        ),
        migrations.RenameField(
            model_name='seomyeon',
            old_name='이름',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='seomyeon',
            old_name='검색어',
            new_name='search_word',
        ),
        migrations.RenameField(
            model_name='seomyeon',
            old_name='경도',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='seomyeon',
            old_name='위도',
            new_name='y',
        ),
    ]
