# Generated by Django 3.1 on 2020-09-02 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200902_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seomyeon',
            old_name='angry',
            new_name='store_angry',
        ),
        migrations.RenameField(
            model_name='seomyeon',
            old_name='category',
            new_name='store_category',
        ),
        migrations.RenameField(
            model_name='seomyeon',
            old_name='happy',
            new_name='store_happy',
        ),
        migrations.RenameField(
            model_name='seomyeon',
            old_name='sad',
            new_name='store_sad',
        ),
        migrations.RenameField(
            model_name='seomyeon',
            old_name='surprised',
            new_name='store_surprised',
        ),
    ]
