# Generated by Django 3.1 on 2020-09-02 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200902_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seomyeon',
            old_name='name',
            new_name='stroe_name',
        ),
    ]
