# Generated by Django 3.1 on 2020-09-02 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200902_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seomyeon',
            old_name='stroe_name',
            new_name='store_name',
        ),
    ]
