# Generated by Django 3.1 on 2020-09-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200902_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seomyeon',
            name='store_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='seomyeon',
            name='x',
            field=models.FloatField(default=0, max_length=10, primary_key=True, serialize=False),
        ),
    ]
