# Generated by Django 3.1 on 2020-09-02 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200902_2335'),
    ]

    operations = [
        migrations.DeleteModel(
            name='seomyeon',
        ),
    ]
