# Generated by Django 3.1 on 2020-09-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_delete_seomyeon'),
    ]

    operations = [
        migrations.CreateModel(
            name='seomyeon',
            fields=[
                ('store_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('store_category', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=50)),
                ('x', models.FloatField(default=0, max_length=10)),
                ('y', models.FloatField(default=0, max_length=10)),
                ('search_word', models.CharField(max_length=50, null=True)),
                ('hashtags', models.CharField(max_length=400, null=True)),
                ('menu', models.CharField(max_length=4000, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('sentiment', models.FloatField(default=0, max_length=10)),
                ('store_happy', models.FloatField(default=0, max_length=10)),
                ('store_sad', models.FloatField(default=0, max_length=10)),
                ('store_angry', models.FloatField(default=0, max_length=10)),
                ('store_surprised', models.FloatField(default=0, max_length=10)),
                ('count', models.IntegerField(default=0)),
                ('WEIGHTED_VOTE', models.FloatField(default=0, max_length=10)),
            ],
        ),
    ]
